### ISSUE TITLE
SolarLog Version

### ISSUE THREAD

**Issue by MrF333** [chrishrb/solarlog-exporter#1]
Hi, there is no information about the current version of the software on the Solarlog or the model. 
Does it also work with software versions 2.X.X ?

**Comment by chrishrb** [comment]
I only have two solar logs, that I could test it with. But I think it works for the newer models also. The script only reads all the files and parses it - so you could test it with your solarLog? 👍 
If you have any issues, please let me know so we could figure out a solution.
